name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1.19.x, 1.20.x, 1.21.x]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=covprofile -v ./...

      - name: Update coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
